# Generated by Django 5.1 on 2024-09-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='adress_1',
            new_name='address_1',
        ),
        migrations.AddField(
            model_name='location',
            name='address_2',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(choices=[('ariana', 'Ariana'), ('beja', 'Beja'), ('ben arous', 'Ben Arous'), ('bizert', 'Bizert'), ('gabes', 'Gabes'), ('gafsa', 'Gafsa'), ('jendouba', 'Jendouba'), ('kairouan', 'Kairouan'), ('kasserine', 'Kasserine'), ('kebili', 'Kebili'), ('kef', 'Kef'), ('mahdia', 'Mahdia'), ('manouba', 'Manouba'), ('medenine', 'Medenine'), ('monastir', 'Monastir'), ('nabeul', 'Nabeul'), ('sfax', 'Sfax'), ('sidi bouzid', 'Sidi Bouzid'), ('siliana', 'Siliana'), ('sousse', 'Sousse'), ('tataouine', 'Tataouine'), ('tozeur', 'Tozeur'), ('tunis', 'Tunis'), ('zaghouan', 'Zaghouan')], default='sfax', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
