# Generated by Django 5.1.1 on 2024-09-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_listing_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='vin',
            field=models.CharField(default=' ', max_length=17),
            preserve_default=False,
        ),
    ]
