# Generated by Django 5.1.1 on 2024-10-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_likedlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='decision',
            field=models.CharField(max_length=50, default='pending'),  # Add a default value here
            preserve_default=False,
        ),
    ]
