# Generated by Django 5.1.1 on 2024-10-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_listing_cost_listing_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='decision',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
