# Generated by Django 5.1.1 on 2024-10-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_listing_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='decision',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
