# Generated by Django 5.1.1 on 2024-10-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_listing_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
