# Generated by Django 5.1.1 on 2024-10-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_listing_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='decision',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('refused', 'Refused')], default='pending', max_length=50),
        ),
    ]
